### ISSUE TITLE
use of cvParam vs. userParam for probeheads

### ISSUE THREAD

**Issue by sneumann** [nmrML/nmrML#125]
Hi,
currently our mapping file https://github.com/nmrML/nmrML/blob/master/ontologies/nmr-mapping.xml#L74
requires the "NMR instrument" and "NMR probe" to be present. Files converted by @djacob65 
extract the probe from the vendor format, and have for @rsalek 's MTBLS1 
< userParam name="ProbeHead" value="5 mm PATXI 1H-13C/15N XYZ-GRD Z561501/0002"/ >

So, do we start to implement manymanymany mappings between ProbeHeads and nmrCV,
or do we drop the mapping file requirement of a < cvParam > for the ProbeHead ?

**Comment by sneumann** [comment]
This seems to be related to #53

**Comment by DSchober** [comment]
I think we don't need all these mappings and maybe capturing the Probe via 
 < userParam name="ProbeHead" value="5 mm PATXI 1H-13C/15N XYZ-GRD Z561501/0002"/ >
is enough.
