### ISSUE TITLE
Attributes order in nmrML file

### ISSUE THREAD

**Issue by JieHao** [nmrML/nmrML#128]
Dear All,

Does anyone know how to set standard DOM automatically read attributes by saving order or do I have to specify each of the attribute order?

When reading nmrML file by standard DOM, it seems can only give the attributes in alphabetical order, this results a different nmrML file (just by the order of attributes)  when I trying to write back into nmrML format. 

It looks like some of the attributes should appear first, like 'id' and 'cvRef' etc, or, does the order not matter?

Many thanks!

Jie

**Comment by djacob65** [comment]
Hi Jie,

I'm afraid you can not avoid the use of a nmrML object (creation,
populating, modification, extension, then reverse conversion).

Best,
Daniel


2015-04-01 10:27 GMT+02:00 JieHao <notifications@github.com>:

**Comment by JieHao** [comment]
Thanks a lot Daniel.
Best
Jie
________________________________
