### ISSUE TITLE
NMR spectrum by phase state

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#129]
@nmrML/nmr-ml-developers 

are this class and subtypes really needed? What are these meant for?
having the sample phase + spectrum should allow retrieving the requirement information.

currently, should we consider deprecating those classes ? If not, provide an example of usage + query

thx

**Comment by DSchober** [comment]
I think these can be deprecated if the phase is indicated at sample level.
Cheers, Daniel.

Am 01.04.2015 um 15:49 schrieb Philippe Rocca-Serra:
>
> @nmrML/nmr-ml-developers 
> <https://github.com/orgs/nmrML/teams/nmr-ml-developers>
>
> are this class and subtypes really needed? What are these meant for?
> having the sample phase + spectrum should allow retrieving the 
> requirement information.
>
> currently, should we consider deprecating those classes ? If not, 
> provide an example of usage + query
>
> thx
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nmrML/nmrML/issues/129>.
>

-- 

Dr. Daniel Schober
Leibniz Institute of Plant Biochemistry, http://www.IPB-Halle.de
Dept. for Stress and Developmental Biology Bioinformatics & Mass Spectrometry
Weinberg 3 Tel. +49 (0) 345 5582 - 1476
06120 Halle

**Comment by DSchober** [comment]
Indeed this was redundant information.  have retired these spectrum classes now. Thanks PRS.
