### ISSUE TITLE
are "quality check result & NMR quality check result" needed?

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#130]
Are there examples / query cases to justify these 2 classes?
Also check the circular / useless definitions:
quality check result  = A quality check result is the usefull outcome of a quality check.
(quality check itself is not defined and deprecated)
NMR quality check result = def: A result of an NMR quality check.

are these used in the validation process?

suggestion: drop both classes

**Comment by DSchober** [comment]
I think these were introduced back in 2006 at EBI when the CIMR was just 
in development and having a future quality assurance use case in mind. 
As we dropped quality check anyway, we here can delete these as well 
now. They have no subclasses anyway.
Cheers, Daniel

Am 02.04.2015 um 00:08 schrieb Philippe Rocca-Serra:
>
> Are there examples / query cases to justify these 2 classes?
> Also check the circular / useless definitions:
> quality check result = A quality check result is the usefull outcome 
> of a quality check.
> (quality check itself is not defined and deprecated)
> NMR quality check result = def: A result of an NMR quality check.
>
> are these used in the validation process?
>
> suggestion: drop both classes
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nmrML/nmrML/issues/130>.
>

-- 

Dr. Daniel Schober
Leibniz Institute of Plant Biochemistry, http://www.IPB-Halle.de
Dept. for Stress and Developmental Biology Bioinformatics & Mass Spectrometry
Weinberg 3 Tel. +49 (0) 345 5582 - 1476
06120 Halle

**Comment by DSchober** [comment]
They are not used so far.
I have retired quality check result and moved NMR quality check result under NMR spectrum descriptor, relabeling to 'NMR quality check descriptor".
