### ISSUE TITLE
quadrature detection, child of 'encoding' . Is this right?

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#131]
@sneumann @djacob65 @LuisFF @rsalek @wilsonmichael @DSchober 

2 suggestions: 
1. change label from 'encoding' to 'signal encoding' 
2.  move 'quadrature detection' (and child class) to the same level as classes such as 'phase-correction', 'time domain data processing' or 'frequencing domain data processing'

Does anything have an explanation as to why it is currently under 'data encoding' ? (we would need a definition for 'data encoding' by the way).

Thanks

Philippe

**Comment by proccaserra** [comment]
one more thing: 'data encoding' or 'frequency encoding'?

**Comment by rsalek** [comment]
> On 2 Apr 2015, at 14:03, Philippe Rocca-Serra <notifications@github.com> wrote:
> 
> @sneumann @djacob65 @LuisFF @rsalek @wilsonmichael @DSchober
> 
> 2 suggestions: 
> 1. change label from 'encoding' to 'signal encoding' 
> 

Not sure , encoding could be  frequency-encoding, phase-encodin, not always a signal 
> 2. move 'quadrature detection' (and child class) to the same level as classes such as 'phase-correction', 'time domain data processing' or 'frequencing domain data processing'
> 

Don't think so, one is about processing and then other acquiring data. Need context. See;

 http://u-of-o-nmr-facility.blogspot.co.uk/2008/08/what-is-quadrature-detection.html?m=1

> Does anything have an explanation as to why it is currently under 'data encoding' ? (we would need a definition for 'data encoding' by the way).
> 

If I remember we had discussions on this but still needs some work

**Comment by proccaserra** [comment]
I have used the same link for obtaining information, but nowhere to they mentioned 'encoding'.

The following document is I feel much better at explaining when and why 'quadrature detection' is used:
http://www.chemeddl.org/alfresco/service/api/node/content/workspace/SpacesStore/915d785a-54ec-4259-a8c6-eeb5d4b0c55a/IntroNMR.pdf?guest=true

Based on the current restrictive and limited definition of encoding (i quote: "A data processing  which compresses a data file for a specific purpose") , the document I  point to describes  'quadrature detection' as a separate process, distinct from 'encoding (*)', which as a very specific purpose. Hence, the request to move it away and not declare it as a subtype of encoding .

(*): based on the current definition of 'encoding', the class label should in fact, read 'data compression'
which would still leave us to define more clearly what we refer to when discussing about 'encoding' {data encoding, frequency encoding,signal encoding...} 
thx.

**Comment by DSchober** [comment]
change label from 'encoding' to 'data encoding'.
Moved  'quadrature detection'  one up according to PRS suggestion and added metadata.
