### ISSUE TITLE
radon encoding

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#132]
@DSchober  @rsalek @LuisFF @khaug @djacob65 ,@sneumann 

Who has a definition for that class? what is its purpose?

Does it refer to 'Radon transformation'. Did you mean 'Radon transform frequency encoding' ?

http://msi-workgroups.sourceforge.net/chemical-analysis/reporting/rubtsovetal_supp.pdf mentions the Radon as a type of encoding but no further detail is provided.

**Comment by rsalek** [comment]
Relates to MRI imaging as far as I can tell;

http://en.m.wikipedia.org/wiki/Radon_transform

Best Wishes,

Reza

**Comment by rsalek** [comment]
Same as Fourier transform; 

http://en.m.wikipedia.org/wiki/Fourier_transform

Best Wishes,

Reza

**Comment by proccaserra** [comment]
Hi Reza, I also found that it seemed first and mainly applied to NMR based imaging.
But this is only one side of the question: is it a process part of the frequency encoding or just one of the frequency to time domain transformation. 
Currently, it is asserted under 'data encoding', possibly solely on the basis of the hierarch found in the pdf produced many years ago by MSI. In the absence of information, reference or pointer to documentation, I have to ask the group.
Also, if it is more specific to imaging application, should it be there?
thx

**Comment by rsalek** [comment]
I would guess "frequency to time domain transformation."

Let's keep it incase of future application.

**Comment by DSchober** [comment]
Have checked and moved this under purgatory. (Google does not come upo with any mention in NMR context.)
