### ISSUE TITLE
Deprecate: "scaling by glog transform optimisation" (NMR:1000076)

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#133]
duplicate of 'scaling by generalized logarithmic transformation' (NMR:1000083)

as glog = generalized logarithmic transformation'

**Comment by DSchober** [comment]
Good spot. Will Deprecate this.

**Comment by proccaserra** [comment]
it is already deprecated in the pull request I sent earlier today.
Do check the commit message for more information and the pull request before making edits to the main.
Retrofitted the edit manually would be quite inefficient.
Yours

**Comment by DSchober** [comment]
DONE.
