### ISSUE TITLE
are linear prediction methods (fwd or bwd) really scaling methods?

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#134]
@LuisFF @nmrML/nmr-ml-developers @wilsonmichael @djacob65 @rsalek @DSchober 

Currently, 3 methods using 'linear prediction' are subclassed as 'scaling methods' in nmrCV:
-back calculation of first points by linear-prediction
-scaling by forward linear prediction
-scaling by mirror image linear prediction

reading more about 'linear prediction' and NMR data processing, it seems that 'linear prediction' is more akin to 'zero filling' ie a method to improve on signal acquisition (at the beginning or the end) of the FID and extrapolate on the data.

I'd like to check with the group on this and whether we would be change the class label from 'scaling' to 'data extrapolation using linear prediction' and not making a child of scaling.

Also, if you have any references/papers detailing the approach, it would be great to have pointers.

thx

**Comment by rsalek** [comment]
Seems ok to me

**Comment by rsalek** [comment]
Clarification, I agree with Philippe on this.

**Comment by DSchober** [comment]
OK, if the term "scaling", which seems to be widely used is appearing at 
least somewhere in that class terminological metadata.

Am 03.04.2015 um 21:09 schrieb Reza Salek:
>
> Clarification, I agree with Philippe on this.
> > On 3 Apr 2015, at 17:41, Philippe Rocca-Serra 
> <notifications@github.com> wrote:
> >
> > @LuisFF @nmrML/nmr-ml-developers @wilsonmichael @djacob65 @rsalek 
> @DSchober
> >
> > Currently, 3 methods using 'linear prediction' are subclassed as 
> 'scaling methods' in nmrCV:
> > -back calculation of first points by linear-prediction
> > -scaling by forward linear prediction
> > -scaling by mirror image linear prediction
> >
> > reading more about 'linear prediction' and NMR data processing, it 
> seems that 'linear prediction' is more akin to 'zero filling' ie a 
> method to improve on signal acquisition (at the beginning or the end) 
> of the FID and extrapolate on the data.
> >
> > I'd like to check with the group on this and whether we would be 
> change the class label from 'scaling' to 'data extrapolation using 
> linear prediction' and not making a child of scaling.
> >
> > thx
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nmrML/nmrML/issues/134#issuecomment-89393420>.
>

-- 

Dr. Daniel Schober
Leibniz Institute of Plant Biochemistry, http://www.IPB-Halle.de
Dept. for Stress and Developmental Biology Bioinformatics & Mass Spectrometry
Weinberg 3 Tel. +49 (0) 345 5582 - 1476
06120 Halle

**Comment by DSchober** [comment]
Checked this, and did proceed according to PRS suggestion by moving the class up and relabeling to "data extrapolation using linear prediction".

**Comment by DSchober** [comment]
removed under time domain data processing/FID zero filling.
