### ISSUE TITLE
Reference to a File is not a File-> check all definitions of 'data file' class and children

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#135]
@sneumann @LuisFF @rsalek @khaug @nmrML/nmr-ml-developers @wilsonmichael 
I was reading the definition for 'data file' and many of the children.
data file: a reference to a file

I don't these definitions are correct.

**Comment by DSchober** [comment]
These definitions suffer from the good old 'use-mention' problem. I think they came form J Cruz. Yes, I will overhaul these. Thanks.

**Comment by proccaserra** [comment]
@DSchober , again the pull request addresses most of these issues. Just read the commit and check the file, otherwise you will duplicate the work.

**Comment by DSchober** [comment]
Have checked and these seem ok now.
