### ISSUE TITLE
T1/T2 relaxation spectra: are those needed?

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#137]
@nmrML/nmr-ml-developers 
@sneumann @rsalek @djacob65 @DSchober @LuisFF @wilsonmichael .

Relaxation is a central process for NMR spectroscopy but is there really such thing as a T1 relaxation spectrum or a T2 relaxation spectrum?
Who has requested those? I can not find publication or references using such terms.
but we would need T1/T2 relaxation and corresponding time measurement (provided this piece of information would be queried).

Thoughts?

Best
Phil

**Comment by DSchober** [comment]
Not sure where these came from, might be something that was indicated by 
our old EBI textmining aproach with Irina Spasic back then, or the 
superclasses were added just to have a place to put T1rho relaxation. I 
think these should indeed be refactored or obsoleted overall as there 
are no more subclasses. Or @sneumann <https://github.com/sneumann>, 
could you do a grep with these terms in the nmrML examples directory to 
see if they are used anywhere?

Am 08.04.2015 um 20:21 schrieb Philippe Rocca-Serra:
>
> @nmrML/nmr-ml-developers 
> <https://github.com/orgs/nmrML/teams/nmr-ml-developers>
> @sneumann <https://github.com/sneumann> @rsalek 
> <https://github.com/rsalek> @djacob65 <https://github.com/djacob65> 
> @DSchober <https://github.com/DSchober> @LuisFF 
> <https://github.com/LuisFF> @wilsonmichael 
> <https://github.com/wilsonmichael> .
>
> Relaxation is a central process for NMR spectroscopy but is there 
> really such thing as a T1 relaxation spectrum or a T2 relaxation spectrum?
> Who has requested those? I can not find publication or references 
> using such terms.
> but we would need T1/T2 relaxation and corresponding time measurement 
> (provided this piece of information would be queried).
>
> Thoughts?
>
> Best
> Phil
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nmrML/nmrML/issues/137>.
>

-- 

Dr. Daniel Schober
Leibniz Institute of Plant Biochemistry, http://www.IPB-Halle.de
Dept. for Stress and Developmental Biology Bioinformatics & Mass Spectrometry
Weinberg 3 Tel. +49 (0) 345 5582 - 1476
06120 Halle

**Comment by DSchober** [comment]
I moved these T1 and T2 relaxation spectrum terms into the purgatory for now... although the fixed term appears as a string in some papers, i.e. as seen in this google search:
https://www.google.de/search?q=NMR+T1+relaxation+spectrum&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=fMQyWNfABITZ8AePg6Ag#q=NMR+%22T1+relaxation+spectrum%22

**Comment by djacob65** [comment]
The T1 relaxation spectrum is recorded to get the T1 of each resonance pattern of interest. This is usually done with a special sequence called inversion-recovery method.

This is of particular interest, if “absolute” quantitative 1H  NMR spectrum set  have to be recorded  ( d1 has to be 5 times the longest  T1 observed in the inversion-recovery spectra).

Have a look on the first picture of this document to get an example of such spectra : https://www2.chemistry.msu.edu/facilities/nmr/handouts/T1%20Measurement.pdf  
 
Regards,
Catherine Deborde
Bordeaux Metabolome Facility
