### ISSUE TITLE
are traf and trafs trapezoid window function?

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#138]
in fact 2 questions @DSchober @nmrML/nmr-ml-developers 

i. is TRAF really a trapezoid window function?
how is this classification made? 
based on http://tesla.ccrc.uga.edu/courses/bionmr/labs/mnova-nmr-tutorial-2014.pdf
and  D.D.Traficante and D.Ziessow, J. Magn. Reson., 66, 182-186, (1986), it does not seem to be case.
@DSchober , what is the source you have used?

ii. what is the difference between 'TRAF' and 'TRAFS' window functions?

in the absence of source information or definition, the class label may be confusing

Thanks for a clarification/explanation

Philippe

**Comment by DSchober** [comment]
We should move it to windor function then. It seems to me it was erroneously assumed to stem from an Acronym from TRApezoid Function, whereas it really setms from the inventors name.
TRAFS comes form 
Traficante window multiplication [traf, trafs], Bruker XWIN parameter
(see http://triton.iqfr.csic.es/guide/nmr/smanual/7l_proc1d.html#7.12.6 )

**Comment by proccaserra** [comment]
@DSchober, a tip: nothing as good as reading the original manuscript. TRAF is an acronym for  "Transform of Reverse Added FIDs" as described by Daniel Traficante in their original paper. No need to second guess, which would have again lead to erroneous conclusions. 
TRAFs seems to be implementation specific to Bruker Xwin and it is currently unclear to me if it justifies a specific class

**Comment by DSchober** [comment]
cleared window function issues...
Moved Trafs from Trapezoid up to window function class
Thanks Phillipe.
