### ISSUE TITLE
JEOL DX duplicates of JCAMP format

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#139]
a jcamp file format has extension .dx or .jdx.
based on class label (and in the absence of other metadata) JEOL DX format seems to indicate a file with .dx extension produced by JEOL instrument.

if not, then specifics must be added

**Comment by djacob65** [comment]
I confirm. It is 'dx'

**Comment by DSchober** [comment]
Yes, JEOL DX format indicates a file with .dx extension produced by JEOL instrument.
No changes needed here.

**Comment by proccaserra** [comment]
@DSchober, a change is needed: JEOL DX format needs to be deprecated, and closing the issue should only be done when this action is performed, ideally with a commit

**Comment by DSchober** [comment]
There are more file formats for the specific Vendors, a few are indicated at 
http://www.acdlabs.com/products/fileformats/   (see below)
This branch actually does not indicate the actual file extensions, but rather mentions the Vendor software for which then the specific FID and parameter files with extensions would be put under data file/FID file and acquisition parameter file respectively.

Not sure how relevant Jeol be in the future. It looks like this particular class described MS data anyway. Now after looking into it, I agree it should be deprecated here.

Here a more extensive list of file extension to Vendor associations (from link above):	
Agilent (Varian, Inc.) 	data, *.fdf, fid0001.fdf, *.txt, fid, phasefile 	acq, proc, procpar 	acq_2, text
Bruker Corporation 	ser, rr, .fid, *r, 1i, 2rr,
*.* (DISNMR) 	acqus, procs, acqu2, proc2s, *.fqs, *.fa1, *.fa2, *.fp1, *.fp2 	title, intrng, *.tit, *.ti2
JCAMP† 	*.dx; *.jdx 		
JEOL Ltd. 	*.als, *.nmfid, *.nmf, *.nmdata, *.nmd, *.gxd, *.bin, *.* (Delta) 	*.gxp, *.hdr 	exp.param, exp.par
Tecmag 	*.tnt, *.* (MacNMR)
