### ISSUE TITLE
JEOL Magnet / JEOL ECA spectrometer /JEOL NMR instrument

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#140]
@DSchober @nmrML/nmr-ml-developers 

Duplication and ambiguity:
http://nmrML.org/nmrCV#NMR:1000274 JEOL ECA spectrometer is asserted under JEOL magnet.

http://nmrML.org/nmrCV#NMR:1400228 ECA is asserted as 'JEOL NMR instrument'

causing a duplication.

IMPORTANT: needs to clarify if a magnet is_a NMR instrument or part_of NMR instrument.

This issue also affect Bruker Magnet/Instrument as Bruker Avance is found under Bruker NMR instrument but Bruker Ultrashield is found under Bruker Magnet

**Comment by DSchober** [comment]
NMR magnet is currently binned under "cardinal part of NMR instrument", which is correct.
I agree the duplication is ugly at the moment and we might want to correlate the different magnet and instrument brances with each other ( I know DL patterns could be used here) and make the naming more explicit, i.e. add the magnet postfix to all magnets and spectrometer to all instruments.

 I am not sure if for all NMR Instruments a separate Magnet needs to be specified.If not we might just keep the one instrument branch. 
 We also wait for the Bruker product catalogue as Tabular data for inclusion here.

**Comment by DSchober** [comment]
cleaned up this area, now distinguishing Magnet form whole instruments. All JEOL instruments have been added/updated. MOre magnets to be included when needed/requested.
