### ISSUE TITLE
Website OWL is out of date

### ISSUE THREAD

**Issue by rsalek** [nmrML/nmrML#144]
Dear All,

The OWL file on the website and github don't match and needs to be updated on the website.
Reza

**Comment by DSchober** [comment]
Yes, overhauling the website will be done before submission of the paper.
Cheers, Daniel.

Von meinem Sony Xperia™-Smartphone gesendet

Reza Salek <notifications@github.com> schrieb:



Dear All,

The OWL file on the website and github don't match and needs to be updated on the website.
Reza

**Comment by althonos** [comment]
*it's actually not the OWL file that's out of date, the examples are (they are not the same as the ones in the GitHub pages, and contains what seem to be references to the previous version of the owl ontology, which is up to date).

**Comment by rsalek** [comment]
Suggested changing "instrument model" currently Bruker .... to "instrument make" as there are several models for each manufacturer , So e.g Instrument Make = Bruker,  Instrument Model = DRX700

**Comment by DSchober** [comment]
All these will now be overhauled.
