### ISSUE TITLE
Instrument make and model

### ISSUE THREAD

**Issue by rsalek** [nmrML/nmrML#145]
Suggested changing "instrument model" currently Bruker .... to "instrument make" as there are several models for each manufacturer , So e.g Instrument Make = Bruker, Instrument Model = DRX700. so Model would be subclass of Make.

In mzML is: "Instrument" and "Instrument Manufacturer" 

There are also lots of redundancies in InstrumentConfiguration

**Comment by DSchober** [comment]
Do you refer to the CV or to the XSD or the nmrML xml ? I can't find "instrument model" there.
in the xml I see 
 <instrumentConfigurationList>
        <instrumentConfiguration id="ID00005">
            <cvParam cvRef="NMRCV" accession="NMR:1000489" name="Varian NMR instrument"/>
            <userParam name="ProbeHead" value="HCN_rt"/>
            <softwareRef ref="ID00004"/>
        </instrumentConfiguration>

**Comment by rsalek** [comment]
CV I believe

**Comment by DSchober** [comment]
In the CV we have separate instrument vendor and instrument model and 
NMR instrument. Tha latter represents the model, so I will retire the 'instrument model' term.  i.e. we have the instrument being labeled via its make/model name. This will then be in harmony to what mzML does, i.e.
mz:Instrument = NMR:NMR instrument 
mz:Instrument Manufacturer = NMR: NMR instrument manufacturerr

**Comment by djacob65** [comment]
If the instrument model is not specified it will be difficult to make the difference between Bruker 500 MHz ( Avance I) and   Bruker 500 MHz ( Avance III).

Electronic is really different in this case (for shimming and for acquisition) and could explain difference in the spectrum quality (ex lineshape width) and thus quantification.

So where such pieces of information are stored in NMR CV?
 
Regards, 
Catherine Deborde 
Bordeaux Metabolome Facility

**Comment by rsalek** [comment]
@althonos can you feedback please?

**Comment by DSchober** [comment]
We can specify the model be adden a CV term under "NMR instrument" (which lists all the models you mention). The acquisition Frequency is found in the XSD under irradiationFrequency, which is mandatory.
Si, I believe we have both data items needed for searches, right ?
