### ISSUE TITLE
Examples are not valid XML

### ISSUE THREAD

**Issue by althonos** [nmrML/nmrML#146]
Hi there,
my xml parser (lxml) raised an error when trying to parse the following files:
- examples/IPB_HopExample/nmrMLs/FAM013_AHTM.PROTON_04.nmrML
- examples/reference_spectra_examples/bmrb/bmse000325.nmrML

I tried with another one (python stdlib xml.etree.ElementTree) and it also fails, which makes me believe those files are not valid.

**Comment by DSchober** [comment]
Hi, 
 Yes, we have concentrated on other examples like 
recently, so the ones you pointed to could be quite outdated. We have fresher Hop examples in the C:\nmrML\examples\IPB_HopExample\nmrMLs.v2 folder , but still, these could be outdated.
I guess the best / updated examples are the one from MTBLS1, e.g. 
MTBLS1/nmrMLs/ADG10003u_007-jnmrML.nmrML
and
examples\reference_spectra_examples\hmdb

**Comment by althonos** [comment]
Yes I know, i've been using them all (https://travis-ci.org/althonos/nmrml2isa), but it's just that I wasn't sure you were aware those examples were invalid.

**Comment by DSchober** [comment]
Are overhauled at the moment to ba all valid at release.
