### ISSUE TITLE
non-english language for Label causes class name display problem in Protege

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#151]
![image](https://cloud.githubusercontent.com/assets/517736/20718574/1580dec8-b651-11e6-9a62-0eeeeaedd10f.png)

caused by

attribute Lang set to 'de' instead of 'en' for rdfs:Label

![image](https://cloud.githubusercontent.com/assets/517736/20718604/34d62990-b651-11e6-99f5-c2050541fd35.png)

**Comment by DSchober** [comment]
done
