### ISSUE TITLE
create_date attribute is not used for record creation_date

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#154]
it seems to be recording the last commit date.
The artifact was created some years ago

**Comment by DSchober** [comment]
Can you point me to the definition of OBO #creation_date ?
Could not find it on http://www.geneontology.org/formats/oboInOwl 
Without any documentation, I assume this refers to the entity annotated and refers to the date this particular entity was created. Not sure here, if it refers to 'initial creation date', then Chis should relabel...
