### ISSUE TITLE
use CHEBI identifiers and import CHEBI entries for chemical entities

### ISSUE THREAD

**Issue by proccaserra** [nmrML/nmrML#159]
NMRML-CV should not mint identifiers for chemical entities but reuse identifiers from reference resources such as CHEBI where terms have been submitted.

CHEBI is the reference resources for chemical entities under COSMOS and PhenoMenal.

see:
https://github.com/nmrML/nmrML/pull/136/commits/ef338aa6537a43bb29b9e0eb3ee58ad287c22bd4

**Comment by rsalek** [comment]
This would be great can get @jkchang2015 help for this

**Comment by proccaserra** [comment]
@rsalek somehow done already, see:
https://github.com/nmrML/nmrML/pull/136/commits/ef338aa6537a43bb29b9e0eb3ee58ad287c22bd4

I submitted a number of chemicals to chebi at that time.

**Comment by rsalek** [comment]
thx
