### ISSUE TITLE
How to describe solvent mixture

### ISSUE THREAD

**Issue by yokochi47** [nmrML/nmrML#162]
Dear all,

I am writing a converter for BMRB metabolomics spectral database and have a trouble with description of solvent mixture. For example, deuterated chloroform (CHEBI_85365) 65% and dueterated methanol (CHEBI_16236, pointing methanol though) 35%. There is "solventType" element in "SampleType" complexType schema component. Is it possible to repeat "solventType"? But, I don't think so.
Furthermore, "solventConcentration" element is ambiguously assigned in the solvent mixture case.
Is there any solution?

Best regards,

Masashi Yokochi,
PDBj-BMRB@Osaka University

**Comment by DSchober** [comment]
Dear Masashi, 
 We are glad to hear about your BMRB efforts and will try to help duely.
For the "solventType" type="CVTermType" element we have not set min or maxCardinality, so technically you can apply it multiple times. But I think we might switch its type from type="CVTermType" to 
type="CVParamTermType". Elements of this type hold additional data or annotation, i.e. a controlled term describing a parameter (e.g. SolventName From CVterm: CHEBI_85365, as well as a value (e.g. 65) and a description of the unit the value (e.g. 'percent', UO:0000187) is recorded in.
You would then iterate through your solvents and assign them with their concentrations as above, by instantiating the  "solventType" type="CVParamTermType" element an additional times for the deuterated Methanols 35 %.

Mike and DanielJ, would this be a feasable XSD change ? Additional comments ?

Here is the full specification of our CVParamTermType from the current XSD:
```
 <xs:complexType name="CVParamWithUnitType">
    <xs:annotation>
      <xs:documentation>This element holds additional data or annotation. Only controlled values are
        allowed here.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="cvRef" type="xs:IDREF" use="required">
      <xs:annotation>
        <xs:documentation>A reference to the CV 'id' attribute as defined in the cvList in this
          nmrML file.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="accession" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The accession number of the referred-to term in the named resource (e.g.:
          NMR:000012).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The actual name for the parameter, from the referred-to controlled
          vocabulary. This should be the preferred name associated with the specified accession
          number.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="value" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>The value for the parameter; may be absent if not appropriate, or a
          numeric or symbolic value, or may itself be CV (legal values for a parameter should be
          enumerated and defined in the ontology).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="unitCvRef" type="xs:IDREF" use="optional">
      <xs:annotation>
        <xs:documentation>If a unit term is referenced, this attribute must refer to the CV 'id'
          attribute defined in the cvList in this nmrML file.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="unitAccession" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>An optional CV accession number for the unit term associated with the
          value, if any (e.g., 'UO:0000266' for 'electron volt').</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="unitName" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>An optional CV name for the unit accession number, if any (e.g., 'electron
          volt' for 'UO:0000266' ).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
```

**Comment by djacob65** [comment]
Dear Daniel,

You mean 'CVParamType' , to change in place of CVTermType !
With oXygen it is a child game ! But the issue is about the nmrML files already filled with a CVTemType for the solvent. How many are actually disseminated in the nature ? Probably none.
If no one has any objection, let's go in that way.

Cheers
Daniel J.

**Comment by djacob65** [comment]
Oups! you're right.  CVParamWithUnitType !!

**Comment by DSchober** [comment]
Alternatively we could be less strict and allow both types ? Also, as it mighjt be overkill to enforce all that CVParamWithUnitType attribute details when in many cases a simple CVTerm would suffice. How does your vendor to nmrML format converter cope with this ? If this does not cause problems, and Masashi is pleased with our solution, then please do the XSD update. But for now lets wait for further feedback for this week.
Cheers, 
   DanielS

**Comment by djacob65** [comment]
"CVParamWithUnitType" is perfect.
Therefore, it means that if we specify only one substance, we have to consistently add  100% (value="100", UO, UO:0000165, volume percentage) as CV unit. 
Cheers
Daniel J.

**Comment by yokochi47** [comment]
Thank you for agile responses.
I will accept "CVParamWithUnitType" for "solventType" provisionally ahead of official update.

Best regards,
Masashi

**Comment by DSchober** [comment]
As Masashi is fine with our proposed solution, I guess its save to implement the required XSD changes (add allowing CVParamWithUnitType for solventType ). DJ, can you do this ?

**Comment by DSchober** [comment]
AAh, I see you already implemented the switch. So we really ONLY allow CVParamWithUnitType for solventType and not the additional old simple CVTermType ? 
If we merely switch, then we should also remove the following 
`<xs:element name="solventConcentration" type="ValueWithUnitType"/>`
specification in the XSD. 
Not sure regarding backwards compatibility as well... ?
