### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by yokochi47** [nmrML/nmrML#164]
Hi,

AtomAssingmentAnnotationType complexType could be AtomAssignmentAnnotationType.
Could you please fix the typo error in nmrML.xsd?

Best regards,

Masashi

**Comment by DSchober** [comment]
Good spot. DanielJ or me will correct the typo in the nmrML.xsd and Ana Marcu will make the NMR-Assign/Baysil parsers aware of this change.
Thank you very much, 
   Daniel Schober
