### ISSUE TITLE
value of irradiation frequency not correct

### ISSUE THREAD

**Issue by aporzel** [nmrML/nmrML#167]
example: **irradiationFrequency value="599.800000" unitAccession="UO_0000325" unitName="megaHertz"**

The value seems to be rounded to (or truncated to) one decimal place. This is not accurate enough. A real value of the VAgilent parameter sfrq reads for instance 599.82636313. At least 6 decimal places should be shown.

**Comment by marcugit** [comment]
Hi all! When working with Bayesil I noticed that the JAVA converter outputs this truncated version of the frequency. This affects the final results for Bayesil when uploading an nmrML file.

**Comment by djacob65** [comment]
Oups! It was a mistake in a Regular Expression. Now it's OK and updated on the GitHub.
