### ISSUE TITLE
Example files on webpage have incorrect fidData attributes

### ISSUE THREAD

**Issue by jjhelmus** [nmrML/nmrML#172]
I have been working on adding support for reading nmrML files with [nmrglue](https://github.com/jjhelmus/nmrglue) and noticed whatI  believe are errors with the [example files on the nmrml.org webpage](http://nmrml.org/examples/).  Specifically, the `encodedLength` attribute in examples 2, 3, 4, and 5 does not match the length of the text.  

Additionally, the byteFormat of example 1 appears incorrect.  A reasonable FID with the correct size (65,536 points) is found if the uncompressed and decoded text is interpreted as holding complex64 formatted data (pairs of float32 entried) but the attribute indicates the data is stored as Complex128.

**Comment by sneumann** [comment]
Hi, thanks for the notice, we'll need to check that.
Good night from this side of the Atlantic, yours, Steffen

**Comment by djacob65** [comment]
Hi Jonathan

# Here is a simple R code for testing/checking at what the encodedLength correspond exactly
# The answer is given at the end 

library(XML)
library(base64enc)

what <- "double"
endian <- "little"
sizeof <- 8
compression.type <- "gzip"

filename <- "C:/Workdir/XSD-XML/dev/examples/MMBBI_10M12-CE01-1a.nmrML"
doc = xmlInternalTreeParse(filename)
 
tree <- xmlTreeParse(filename)
root <- xmlRoot(tree)


### ---  Acquisition Parameters -----
acquisition <- xmlElementsByTagName(root, "acquisition", recursive = TRUE)[[1]]

### ---  FID -----
fidData <- xmlElementsByTagName(acquisition, "fidData", recursive = TRUE)

# <fidData compressed="true" encodedLength="101506" byteFormat="Complex128"> ... </fidData>
compression <- ifelse(  xmlAttrs(fidData[[1]])["compressed"]=="true", compression.type, "" )
encodedLength <- as.numeric(xmlAttrs(fidData[[1]])["encodedLength"])

# Read the ASCII characters in the file 
asciiRawData <- gsub("\n", "", xmlValue(fidData[[1]]))

# Convert ASCII characters into HEXA values
raws <- base64decode(asciiRawData)

encodedLength
nchar(asciiRawData)
length(raws)

> encodedLength
[1] 101506
> nchar(asciiRawData)
[1] 135344
> length(raws)
[1] 101506

# It is OK: the 'encodedLength' field corresponds to the size of values before uncompressing

Best
Daniel J.

**Comment by jjhelmus** [comment]
@djacob65 From your example it seems that the intention of the `encodedLength` attribute is to give the length in characters of the decoded base64 string, this seems to be in disagreement with the [description](http://nmrml.org/schema/v1.0.rc1/doc/doc/schema.html#Acquisition1DType_fidData) of the attribute in the documentation: "The number of characters in the base64 string. This is useful for skipping over the string in high throughput applications."

Regardless either definition is inconsistent within the five example files given, one gives the length of the base64 encoded string, three the length of the decoded sting, and in the last example sets this attribute to the number of data points in the FID.

The following Python code finds the length of the XML attribute, the encoded text and the decoded text:


``` Python
import base64
import xmltodict

def find_lengths(filename):
    with open(filename, 'rb') as nmrml_file:
        doc = xmltodict.parse(nmrml_file.read())
    fid_data = doc['nmrML']['acquisition']['acquisition1D']['fidData']
    raw_text = fid_data['#text']
    decoded_text = base64.b64decode(raw_text)
    encoded_length = int(fid_data['@encodedLength'])
    return encoded_length, len(raw_text), len(decoded_text)

filenames = [
    './FAM013_AHTM.PROTON_04.nmrML',
    './MMBBI_10M12-CE01-1a.nmrML',
    './HMDB00005.nmrML',
    './biosample_quantification.nmrML',
    './ADG10003u_007.nmrML',
]

print("Filename\txml_len\tencoded_text_len\tdecoded_text_len")
for filename in filenames:
    xml_len, encoded_text_len, decoded_text_len = find_lengths(filename)
    print(filename, xml_len, encoded_text_len, decoded_text_len)
```

The result formatted into a nice table are as follows:

| Filename | XML | encoded text | decoded text |
| --- | --- | --- | --- |
| FAM013_AHTM.PROTON_04.nmrML | **324160** | **324160** | 243119 |
| MMBBI_10M12-CE01-1a.nmrML | **175328** | 233772 | **175328** |
| HMDB00005.nmrML | **132654** | 176872 | **132654** |
| biosample_quantification.nmrML | **104019** | 138692 | **104019** |
| ADG10003u_007.nmrML | 65536 | 349528 | 262144 |

Also, byteformat attribute of the first example (FAM013_AHTM.PROTON_04.nmrML) also seems to be set incorrectly.

**Comment by djacob65** [comment]
Hi Jonathan,

Indeed ! you are right. 
So let's conform to the definition!

I have updated the JAVA converter in that sense, and also the example file 2.

Thank you for your vigilance !

Best,
Daniel

**Comment by djacob65** [comment]
The issue was solved!
