### ISSUE TITLE
Set versions to 1.0 release tag

### ISSUE THREAD

**Issue by sneumann** [nmrML/nmrML#173]
Hi, as hinted by multiple people, we need to get our versioning in order,
the next tagged version should be 1.0rc2. We have several places 
with currently rc1: https://github.com/nmrML/nmrML/search?utf8=%E2%9C%93&q=rc1&type=Code

**Comment by DSchober** [comment]
fixed in 56bd8ed3b5b625bffa227eea9fd0157915768f1f
