### ISSUE TITLE
ppm range

### ISSUE THREAD

**Issue by jianlianggao** [nmrML/nmrML#180]
Hi Daniel,

I noticed you recently made some change on nmrML converter code. There used to be attributes like "spectrumDataArray" for realdata and "xAxis" for ppm starting/ending. Now they are gone. Instead, you use 
```
intensities <- base64decode(b64s[2], "double", size=8)
.....
numberOfDataPoints <- as.integer(xmlAttrs(xmlElementsByTagName(root, "DirectDimensionParameterSet", recursive = TRUE)[[1]])["numberOfDataPoints"])

    ## delayTime <- 1.0
    ## ppmOffset <- delayTime / 599.4094446,
    
    ppm <- seq(from=14.77180,
               to= -5.239921,
               length=numberOfDataPoints)
```
ppm range is fixed now. What if ppm starting and ending points are different from one to the other? Thank you very much.

Best wishes,
Jianliang

**Comment by djacob65** [comment]
Hi Jianliang

You seem (!?) to make reference to the R code  "https://github.com/nmrML/nmrML/blob/master/tools/Parser_and_Converters/R/reader.R"
It is "a simple example file to demonstrate loading ontologies and parsing an NMR-ML file " as mentioned in its header.

I put in the github a complete R script allowing to read fid / 1r data along with the metadata. Thus you can pick up lines you wish to insert in your own code.
See https://github.com/nmrML/nmrML/blob/master/tools/Parser_and_Converters/R/RnmrML/read_nmrML.R

Best,

Daniel J.

**Comment by jianlianggao** [comment]
Hi Daniel,

Thank you very much for quick reply.

Yes I am referring to the R code.

Are the tags `spectrumDataArray` and `xAxis` deprecated in the latest nmrML converter code?

Best wishes,
Jianliang

**Comment by djacob65** [comment]
See my answer for issue#180 -  https://github.com/nmrML/nmrML/issues/181

**Comment by jianlianggao** [comment]
Hi Daniel,

Thank you very much.

I will try your instruction .

Best wishes,
Jianliang
