### ISSUE TITLE
Update MAF file with Multiplicity Information

### ISSUE THREAD

**Issue by djacob65** [nmrML/nmrML#4]

**Comment by khaug** [comment]
I can add this to the configuration files for NMR, can I have a brief description to use as mouse-over-help please?

**Comment by khaug** [comment]
This is what we have already:

<field header="multiplicity" data-type="String" ......>
            <description>NMR: Type of multiplets observed of the metabolite (e.g s, d, t, q, dd, ...)

**Comment by proccaserra** [comment]
@khaug @DSchober I supposed value should be coming from NMR-CV. parent class multiplet feature=http://nmrML.org/nmrCV#NMR:1400006

@DSchober probably good to add the value described by @khaug as synonyms.

**Comment by DSchober** [comment]
I ahve put all of these in the CV under 'multiplicity feature' class and added the Acronyms (e.g s, d, t, q, dd, ...) as exact synonyms.
