### ISSUE TITLE
NMR instrument type 

### ISSUE THREAD

**Issue by rsalek** [nmrML/nmrML#52]
Major NMR instrument makers include Oxford Instruments, Bruker, Spinlock SRL, General Electric, JEOL, Kimble Chase, Philips, Siemens AG, and Agilent Technologies, Inc. (who own Varian, Inc.).

Bruker list
http://www.bruker.com/products/mr/nmr/

Agilent former Varian

Varian Inova 500
Varian VNMRS
Varian Mercury plus
 Varian UnityInova
400-MR NMR
DDR2
Agilent “Mercury 400”
Agilent Au 400 (DDR2 Console)
Agilent DDR 2 w/ HCN cryoprobe

**Comment by DSchober** [comment]
All put in now.
